# Generated by Django 5.2.16 on 2026-07-22 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='coachprofile',
            name='break_ends_at',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='coachprofile',
            name='break_starts_at',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='coachprofile',
            name='day_ends_at',
            field=models.TimeField(default='20:00'),
        ),
        migrations.AddField(
            model_name='coachprofile',
            name='day_starts_at',
            field=models.TimeField(default='08:00'),
        ),
    ]
