# Generated by Django 5.2.16 on 2026-07-22 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_coachprofile_break_ends_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='coachprofile',
            name='timezone',
            field=models.CharField(default='Europe/Berlin', max_length=64),
        ),
    ]
