# Generated by Django 5.2.16 on 2026-07-23 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_coachprofile_timezone'),
    ]

    operations = [
        migrations.AddField(
            model_name='coachprofile',
            name='offered_topics',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
