# Generated by Django 5.2.16 on 2026-07-21 11:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='availabilityslot',
            new_name='scheduling__coach_i_2d00a1_idx',
            old_name='scheduling__coach_i_28c29b_idx',
        ),
        migrations.RenameIndex(
            model_name='availabilityslot',
            new_name='scheduling__status_afb5ee_idx',
            old_name='scheduling__status_6f25c2_idx',
        ),
    ]
