# Generated by Django 5.2.16 on 2026-07-23 09:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0004_coachprofile_offered_topics'),
        ('scheduling', '0002_rename_scheduling__coach_i_28c29b_idx_scheduling__coach_i_2d00a1_idx_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProposalWindow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('starts_at', models.DateTimeField()),
                ('ends_at', models.DateTimeField()),
                ('location', models.CharField(blank=True, max_length=200)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('coach', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proposal_windows', to='profiles.coachprofile')),
            ],
            options={
                'ordering': ['starts_at'],
                'indexes': [models.Index(fields=['coach', 'starts_at', 'ends_at'], name='scheduling__coach_i_74e470_idx')],
            },
        ),
    ]
