# Generated by Django 5.2.16 on 2026-07-23 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling', '0003_proposalwindow'),
    ]

    operations = [
        migrations.AlterField(
            model_name='availabilityslot',
            name='status',
            field=models.CharField(choices=[('open', 'Open'), ('pending', 'Pending approval'), ('reserved', 'Reserved'), ('cancelled', 'Cancelled')], default='open', max_length=16),
        ),
    ]
