# Generated by Django 5.2.16 on 2026-07-21 11:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='bookingrequest',
            new_name='bookings_bo_coach_i_a103ee_idx',
            old_name='bookings_bo_coach__92a7ab_idx',
        ),
        migrations.RenameIndex(
            model_name='bookingrequest',
            new_name='bookings_bo_student_ad5858_idx',
            old_name='bookings_bo_student_2d36ba_idx',
        ),
        migrations.RenameIndex(
            model_name='session',
            new_name='bookings_se_coach_i_0cb054_idx',
            old_name='bookings_se_coach__d9907a_idx',
        ),
        migrations.RenameIndex(
            model_name='session',
            new_name='bookings_se_student_eb7523_idx',
            old_name='bookings_se_student_c1de52_idx',
        ),
        migrations.RenameIndex(
            model_name='session',
            new_name='bookings_se_status_a6f98e_idx',
            old_name='bookings_se_status_2d35c8_idx',
        ),
    ]
