# Generated by Django 5.2.16 on 2026-07-23 15:51

import django.db.models.deletion
from django.db import migrations, models


def preserve_existing_pending_proposals(apps, schema_editor):
    BookingRequest = apps.get_model("bookings", "BookingRequest")
    ProposalWindow = apps.get_model("scheduling", "ProposalWindow")

    roots = {}
    pending_requests = BookingRequest.objects.filter(status="pending", proposal_window__isnull=True).select_related("slot")
    for booking_request in pending_requests:
        slot = booking_request.slot
        candidates = list(
            ProposalWindow.objects.filter(
                coach_id=booking_request.coach_id,
                active=False,
                starts_at__lte=slot.starts_at,
                ends_at__gte=slot.ends_at,
            )
        )
        if not candidates:
            continue
        root = max(candidates, key=lambda window: window.ends_at - window.starts_at)
        booking_request.proposal_window_id = root.id
        booking_request.save(update_fields=["proposal_window"])
        if slot.status == "open":
            slot.status = "pending"
            slot.save(update_fields=["status"])
        roots[root.id] = root

    for root in roots.values():
        ProposalWindow.objects.filter(
            coach_id=root.coach_id,
            starts_at__gte=root.starts_at,
            ends_at__lte=root.ends_at,
        ).exclude(pk=root.pk).update(active=False)
        ProposalWindow.objects.filter(pk=root.pk).update(active=True)


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0002_rename_bookings_bo_coach__92a7ab_idx_bookings_bo_coach_i_a103ee_idx_and_more'),
        ('scheduling', '0004_alter_availabilityslot_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookingrequest',
            name='cancellation_note',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='bookingrequest',
            name='cancellation_reason_code',
            field=models.CharField(blank=True, choices=[('wrong_input', 'Wrong input'), ('coach_response_delay', 'Too long to answer'), ('schedule_changed', 'Schedule changed'), ('illness', 'Illness'), ('other', 'Other')], max_length=32),
        ),
        migrations.AddField(
            model_name='bookingrequest',
            name='cancelled_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bookingrequest',
            name='proposal_window',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='booking_requests', to='scheduling.proposalwindow'),
        ),
        migrations.AddField(
            model_name='cancellation',
            name='reason_code',
            field=models.CharField(choices=[('wrong_input', 'Wrong input'), ('coach_response_delay', 'Too long to answer'), ('schedule_changed', 'Schedule changed'), ('illness', 'Illness'), ('other', 'Other')], default='other', max_length=32),
        ),
        migrations.RunPython(preserve_existing_pending_proposals, migrations.RunPython.noop),
    ]
