# Generated by Django 5.2.16 on 2026-07-21 11:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='notification',
            new_name='notificatio_user_id_47e85c_idx',
            old_name='notificatio_user_id_1f8309_idx',
        ),
        migrations.RenameIndex(
            model_name='notification',
            new_name='notificatio_kind_e256fc_idx',
            old_name='notificatio_kind_8b5c59_idx',
        ),
    ]
